---
deployment:
  tasks:
    - export DEPLOYPATH=/home1/angel772/tap.amodesenvolvimento.com.br/
    - /bin/cp -R index.html .htaccess sitemap.xml robots.txt llms.txt unidades styles.css app.js theme.css map.css map.js cotacao.css cotacao.js data api atendimento assets frames $DEPLOYPATH
