---
deployment:
  tasks:
    - export DEPLOYPATH=/home1/angel772/tap.amodesenvolvimento.com.br/
    - /bin/cp -R index.html google65464db5c7e06d51.html .htaccess sitemap.xml robots.txt llms.txt pages.css unidades sobre servicos rastreamento cotacao tapia contato cidades privacidade en es zh styles.css app.js theme.css map.css map.js cotacao.css cotacao.js carreiras.js rastreio.js carreiras data api atendimento assets frames $DEPLOYPATH
