---
deployment:
  tasks:
    - export DEPLOYPATH=/home1/angel772/tap.amodesenvolvimento.com.br/
    - /bin/cp -R index.html styles.css app.js theme.css map.css map.js cotacao.css cotacao.js data api atendimento .htaccess assets frames $DEPLOYPATH
